INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Harina 0000', 1000.00, 10, 20);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Camiseta', 15.99, 10, 50);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Pantalón', 29.99, 15, 30);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Zapatos deportivos', 49.99, 20, 25);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Gorra', 12.50, 5, 100);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Bolso de mano', 35.00, 25, 15);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Chaqueta', 60.99, 30, 10);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Reloj digital', 85.00, 10, 40);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Lentes de sol', 19.99, 20, 75);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Bufanda', 8.99, 5, 150);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Guantes', 14.50, 10, 200);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Corbata', 9.99, 15, 60);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Traje', 120.00, 25, 20);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Calcetines', 4.50, 5, 300);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Cinturón', 15.99, 10, 80);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Pijama', 24.99, 20, 50);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Bañador', 18.00, 15, 90);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Sombrero', 22.99, 30, 45);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Mochila', 55.00, 20, 35);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Botas de cuero', 70.99, 25, 40);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Vestido', 45.00, 15, 25);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Sandalias', 20.00, 10, 60);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Gafas de lectura', 12.99, 5, 100);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Polo', 18.50, 20, 80);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Shorts', 16.99, 15, 55);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Zapatos de vestir', 65.00, 30, 15);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Chaleco', 38.50, 10, 45);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Blusa', 29.99, 20, 25);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Pañuelo', 7.50, 5, 120);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Falda', 35.00, 25, 30);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Chal', 19.99, 10, 80);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Bata', 42.50, 20, 20);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Mono', 28.99, 15, 35);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Jeans', 32.99, 20, 50);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Zapatos casuales', 45.50, 25, 40);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Camiseta de deporte', 22.99, 10, 60);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Sudadera', 39.50, 30, 25);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Zapatillas de casa', 12.00, 15, 70);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Camisón', 18.99, 5, 80);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Chaqueta impermeable', 65.99, 20, 30);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Pantalón de chándal', 24.50, 15, 50);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Sombrero de invierno', 14.99, 5, 100);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Camiseta sin mangas', 10.99, 10, 150);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Botines', 59.00, 25, 20);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Falda larga', 27.99, 20, 45);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Gorra de béisbol', 9.50, 10, 120);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Chaleco acolchado', 48.00, 30, 35);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Guantes de lana', 16.50, 15, 90);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Pantalones cortos de deporte', 19.99, 20, 50);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Pantalón vaquero', 44.99, 10, 60);
INSERT INTO productos (nombre_producto, precio, descuento, stock) VALUES ('Cazadora', 55.50, 25, 20);


INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (name) VALUES ('ROLE_USER');
